### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by diego-rapoport** [nix-community/kickstart-nix.nvim#13]
I'm using Arch Linux and I got this issue while running the nix run command to test:
```
error: builder for '/nix/store/ficqvjd27dp1i2409ql4vk10l3ilm7p2-nvim-rtp.drv' failed with exit code 1;                                                                    
       last 4 log lines:                                                                                                                                                  
       > Running phase: unpackPhase                                                                                                                                       
       > unpacking source archive /nix/store/9pc7dbf2wbximglhlrqr6mf8mrsdhfy9-nvim-rtp-src                                                                                
       > cp: setting permissions for 'nvim-rtp-src': Invalid argument                                                                                                     
       > do not know how to unpack source archive /nix/store/9pc7dbf2wbximglhlrqr6mf8mrsdhfy9-nvim-rtp-src                                                                
       For full logs, run 'nix-store -l /nix/store/ficqvjd27dp1i2409ql4vk10l3ilm7p2-nvim-rtp.drv'.                                                                        
error: 1 dependencies of derivation '/nix/store/lz4f1gfyaaw2h57bqzwz23b1jf1v71ci-neovim-0.9.5.drv' failed to build                                                        
```

The full log doesn't provide different information

**Comment by mrcjkb** [comment]
Hey :wave: 

What's the exact command you're using? 

```sh
nix run "github:nix-community/kickstart-nix.nvim
```

or 

```sh
# from a local checkout
nix run
```

Looks like it could be related to https://github.com/NixOS/nixpkgs/issues/302046

**Comment by diego-rapoport** [comment]
I was using the first one!

Will check the issue you linked in here.

**Comment by mrcjkb** [comment]
Something you could try to work around it:

- Clone the repo.
- In `flake.nix`, change the `nixpkgs` input to use `nixos-23.11` instead of `nixos-unstable`.
- Try to run it locally.

**Comment by Ma27** [comment]
> Looks like it could be related to NixOS/nixpkgs#302046

Only if you're running on an oldish lqx kernel. Otherwise it's probably https://github.com/NixOS/nixpkgs/issues/300635.
Will try to come up with a fix for that soon.

**Comment by mrcjkb** [comment]
> > Looks like it could be related to [NixOS/nixpkgs#302046](https://github.com/NixOS/nixpkgs/issues/302046)
> 
> Only if you're running on an oldish lqx kernel. Otherwise it's probably [NixOS/nixpkgs#300635](https://github.com/NixOS/nixpkgs/issues/300635). Will try to come up with a fix for that soon.

Thanks for the insight :smile:

**Comment by diego-rapoport** [comment]
> Something you could try to work around it:
> 
> * Clone the repo.
> * In `flake.nix`, change the `nixpkgs` input to use `nixos-23.11` instead of `nixos-unstable`.
> * Try to run it locally.

That seemed to work fine!

**Comment by mrcjkb** [comment]
Thanks for the update.
I'll close this issue then, since there's not much I can do on this side.

**Comment by diego-rapoport** [comment]
Ok so now it overwrites my neovim system wide. How can I unset this or at least keep mine as default?
I can see that when I run `which nvim` it points to `~/.nix-profile/bin/nvim` which I don't intend to.

**Comment by mrcjkb** [comment]
> Ok so now it overwrites my neovim system wide. How can I unset this or at least keep mine as default? I can see that when I run `which nvim` it points to `~/.nix-profile/bin/nvim` which I don't intend to.

I've created an issue for a solution for that 😃
