### ISSUE TITLE
Error message when opening a .nix file then a .lua file

### ISSUE THREAD

**Issue by Eddio0141** [nix-community/kickstart-nix.nvim#33]
The error I get is `method textDocument/codeLens is not supported by any of the servers registered for the current buffer`. This error pops up on anything I do, writing, escaping to normal mode, etc.

How to do:
1. Open some nix file
2. Open some lua file in the same session (you can use `:e whatever.lua` or `:Explore`, doesn't matter)
3. Try do anything in the lua file, `:w` can cause the error

- Contents of the lua file and nix file doesn't matter, they can be empty
- This doesn't happen when only having lua files opened in the session

**Comment by mrcjkb** [comment]
Hey 👋 

I haven't encountered this with the default setup. 
Is this [with nixd instead of nil](https://github.com/Eddio0141/nvim/commit/7a191b49753acae69b70dc458c21a86cb086f187).

It sounds like the nixd client (which I guess supports code lenses) is somehow attaching to the Lua buffer, which leads to [this autocommand being created](https://github.com/nix-community/kickstart-nix.nvim/blob/842431c0c298a6087f30df962a242e51c8df62c9/nvim/plugin/autocommands.lua#L120).

**Comment by Eddio0141** [comment]
Hiya
This is with the default template unmodified, I directly run `nix run "github:nix-community/kickstart-nix.nvim"` to open some nix file, and then a lua file which causes the error for me

A short clip here goes through exactly what I'm doing

https://github.com/user-attachments/assets/b5ac8a06-47b0-4b71-a100-6d670221ebf9

**Comment by jirafey** [comment]
I am facing the same issue when running the flake with `nix run "github:nix-community/kickstart-nix.nvim"`
open `nix/neovim-overlay.nix` `:e ../kickstart-nix.nvim/nvim/lua/user/lsp.lua` delete a line of code 
make the code look like this for example:
```lua
---@mod user.lsp
---@brief [[
---LSP related functions
---@brief ]]

---Gets a 'ClientCapabilities' object, describing the LSP client capabilities
---Extends the object with capabilities provided by plugins.
---@return lsp.ClientCapabilities
  local capabilities = vim.lsp.protocol.make_client_capabilities()
  -- Add com_nvim_lsp capabilities
  local cmp_lsp = require('cmp_nvim_lsp')
  local cmp_lsp_capabilities = cmp_lsp.default_capabilities()
  capabilities = vim.tbl_deep_extend('keep', capabilities, cmp_lsp_capabilities)
  -- Add any additional plugin capabilities here.
  -- Make sure to follow the instructions provided in the plugin's docs.
  return capabilities
end

return M
```
![image](https://github.com/user-attachments/assets/c89b255f-a81e-4ede-9377-f03a6319f0b9)

**Comment by mrcjkb** [comment]
:thinking: just pulled the latest changes and can reproduce.
It looks like lua-language-server is erroneously reporting that it supports code lenses to the client.

**Comment by mrcjkb** [comment]
Fixed: https://github.com/nix-community/kickstart-nix.nvim/commit/2181d879ce041411f8b8c36c5d6160928631ba85
